### ISSUE TITLE
[ERC20] Add test

### ISSUE THREAD

**Issue by nrryuya** [LayerXcom/verified-vyper-contracts#15]
https://github.com/ethereum/vyper/tree/master/tests/examples/tokens/ERC20_solidity_compatible

**Comment by nrryuya** [comment]
```
(venv) PC-004:ERC20_solidity_compatible ryuya.nakamura$ python run_tests.py 

Failed to import bitcoin. This is not a fatal error but does
mean that you will not be able to determine the address from
your wallet file.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
Running Solidity-compatible ERC20 tests, Suite 1 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Initializing chain from provided state
Initializing chain from provided state
ERROR
Initializing chain from provided state
Initializing chain from provided state
test_deposit_and_withdraw (test.erc20_tests_1.TestSolidity1ERC20) ... ERROR
test_failed_send_in_withdraw (test.erc20_tests_1.TestSolidity1ERC20) ... ERROR
test_initial_state (test.erc20_tests_1.TestSolidity1ERC20) ... ERROR
test_maxInts (test.erc20_tests_1.TestSolidity1ERC20) ... ERROR
test_payability (test.erc20_tests_1.TestSolidity1ERC20) ... ERROR
test_raw_logs (test.erc20_tests_1.TestSolidity1ERC20) ... ERROR
test_totalSupply (test.erc20_tests_1.TestSolidity1ERC20) ... ERROR
test_transfer (test.erc20_tests_1.TestSolidity1ERC20) ... ERROR
test_transferFromAndAllowance (test.erc20_tests_1.TestSolidity1ERC20) ... ERROR
Initializing chain from provided state
Initializing chain from provided state
test_deposit_and_withdraw (test.erc20_tests_1.TestSolidity2ERC20) ... ERROR
test_failed_send_in_withdraw (test.erc20_tests_1.TestSolidity2ERC20) ... ERROR
test_initial_state (test.erc20_tests_1.TestSolidity2ERC20) ... ERROR
test_maxInts (test.erc20_tests_1.TestSolidity2ERC20) ... ERROR
test_payability (test.erc20_tests_1.TestSolidity2ERC20) ... ERROR
test_raw_logs (test.erc20_tests_1.TestSolidity2ERC20) ... ERROR
test_totalSupply (test.erc20_tests_1.TestSolidity2ERC20) ... ERROR
test_transfer (test.erc20_tests_1.TestSolidity2ERC20) ... ERROR
test_transferFromAndAllowance (test.erc20_tests_1.TestSolidity2ERC20) ... ERROR

======================================================================
ERROR: setUpClass (test.erc20_tests_1.TestVyperERC20)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 343, in setUpClass
    cls.t.languages['vyper'] = compiler.Compiler()
AttributeError: module 'vyper.compiler' has no attribute 'Compiler'

======================================================================
ERROR: test_deposit_and_withdraw (test.erc20_tests_1.TestSolidity1ERC20)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 407, in setUp
    super().setUp()
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 52, in setUp
    self.s.revert(self.initial_state)
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/ethereum/tools/tester.py", line 297, in revert
    self.block.transactions = self.block.transactions[:txcount]
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/rlp/sedes/serializable.py", line 334, in field_fn_setter
    raise AttributeError("can't set attribute")
AttributeError: can't set attribute

======================================================================
ERROR: test_failed_send_in_withdraw (test.erc20_tests_1.TestSolidity1ERC20)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 407, in setUp
    super().setUp()
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 52, in setUp
    self.s.revert(self.initial_state)
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/ethereum/tools/tester.py", line 297, in revert
    self.block.transactions = self.block.transactions[:txcount]
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/rlp/sedes/serializable.py", line 334, in field_fn_setter
    raise AttributeError("can't set attribute")
AttributeError: can't set attribute

======================================================================
ERROR: test_initial_state (test.erc20_tests_1.TestSolidity1ERC20)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 407, in setUp
    super().setUp()
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 52, in setUp
    self.s.revert(self.initial_state)
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/ethereum/tools/tester.py", line 297, in revert
    self.block.transactions = self.block.transactions[:txcount]
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/rlp/sedes/serializable.py", line 334, in field_fn_setter
    raise AttributeError("can't set attribute")
AttributeError: can't set attribute

======================================================================
ERROR: test_maxInts (test.erc20_tests_1.TestSolidity1ERC20)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 407, in setUp
    super().setUp()
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 52, in setUp
    self.s.revert(self.initial_state)
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/ethereum/tools/tester.py", line 297, in revert
    self.block.transactions = self.block.transactions[:txcount]
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/rlp/sedes/serializable.py", line 334, in field_fn_setter
    raise AttributeError("can't set attribute")
AttributeError: can't set attribute

======================================================================
ERROR: test_payability (test.erc20_tests_1.TestSolidity1ERC20)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 407, in setUp
    super().setUp()
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 52, in setUp
    self.s.revert(self.initial_state)
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/ethereum/tools/tester.py", line 297, in revert
    self.block.transactions = self.block.transactions[:txcount]
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/rlp/sedes/serializable.py", line 334, in field_fn_setter
    raise AttributeError("can't set attribute")
AttributeError: can't set attribute

======================================================================
ERROR: test_raw_logs (test.erc20_tests_1.TestSolidity1ERC20)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 407, in setUp
    super().setUp()
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 52, in setUp
    self.s.revert(self.initial_state)
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/ethereum/tools/tester.py", line 297, in revert
    self.block.transactions = self.block.transactions[:txcount]
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/rlp/sedes/serializable.py", line 334, in field_fn_setter
    raise AttributeError("can't set attribute")
AttributeError: can't set attribute

======================================================================
ERROR: test_totalSupply (test.erc20_tests_1.TestSolidity1ERC20)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 407, in setUp
    super().setUp()
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 52, in setUp
    self.s.revert(self.initial_state)
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/ethereum/tools/tester.py", line 297, in revert
    self.block.transactions = self.block.transactions[:txcount]
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/rlp/sedes/serializable.py", line 334, in field_fn_setter
    raise AttributeError("can't set attribute")
AttributeError: can't set attribute

======================================================================
ERROR: test_transfer (test.erc20_tests_1.TestSolidity1ERC20)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 407, in setUp
    super().setUp()
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 52, in setUp
    self.s.revert(self.initial_state)
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/ethereum/tools/tester.py", line 297, in revert
    self.block.transactions = self.block.transactions[:txcount]
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/rlp/sedes/serializable.py", line 334, in field_fn_setter
    raise AttributeError("can't set attribute")
AttributeError: can't set attribute

======================================================================
ERROR: test_transferFromAndAllowance (test.erc20_tests_1.TestSolidity1ERC20)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 407, in setUp
    super().setUp()
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 52, in setUp
    self.s.revert(self.initial_state)
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/ethereum/tools/tester.py", line 297, in revert
    self.block.transactions = self.block.transactions[:txcount]
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/rlp/sedes/serializable.py", line 334, in field_fn_setter
    raise AttributeError("can't set attribute")
AttributeError: can't set attribute

======================================================================
ERROR: test_deposit_and_withdraw (test.erc20_tests_1.TestSolidity2ERC20)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 424, in setUp
    super().setUp()
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 52, in setUp
    self.s.revert(self.initial_state)
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/ethereum/tools/tester.py", line 297, in revert
    self.block.transactions = self.block.transactions[:txcount]
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/rlp/sedes/serializable.py", line 334, in field_fn_setter
    raise AttributeError("can't set attribute")
AttributeError: can't set attribute

======================================================================
ERROR: test_failed_send_in_withdraw (test.erc20_tests_1.TestSolidity2ERC20)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 424, in setUp
    super().setUp()
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 52, in setUp
    self.s.revert(self.initial_state)
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/ethereum/tools/tester.py", line 297, in revert
    self.block.transactions = self.block.transactions[:txcount]
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/rlp/sedes/serializable.py", line 334, in field_fn_setter
    raise AttributeError("can't set attribute")
AttributeError: can't set attribute

======================================================================
ERROR: test_initial_state (test.erc20_tests_1.TestSolidity2ERC20)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 424, in setUp
    super().setUp()
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 52, in setUp
    self.s.revert(self.initial_state)
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/ethereum/tools/tester.py", line 297, in revert
    self.block.transactions = self.block.transactions[:txcount]
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/rlp/sedes/serializable.py", line 334, in field_fn_setter
    raise AttributeError("can't set attribute")
AttributeError: can't set attribute

======================================================================
ERROR: test_maxInts (test.erc20_tests_1.TestSolidity2ERC20)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 424, in setUp
    super().setUp()
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 52, in setUp
    self.s.revert(self.initial_state)
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/ethereum/tools/tester.py", line 297, in revert
    self.block.transactions = self.block.transactions[:txcount]
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/rlp/sedes/serializable.py", line 334, in field_fn_setter
    raise AttributeError("can't set attribute")
AttributeError: can't set attribute

======================================================================
ERROR: test_payability (test.erc20_tests_1.TestSolidity2ERC20)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 424, in setUp
    super().setUp()
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 52, in setUp
    self.s.revert(self.initial_state)
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/ethereum/tools/tester.py", line 297, in revert
    self.block.transactions = self.block.transactions[:txcount]
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/rlp/sedes/serializable.py", line 334, in field_fn_setter
    raise AttributeError("can't set attribute")
AttributeError: can't set attribute

======================================================================
ERROR: test_raw_logs (test.erc20_tests_1.TestSolidity2ERC20)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 424, in setUp
    super().setUp()
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 52, in setUp
    self.s.revert(self.initial_state)
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/ethereum/tools/tester.py", line 297, in revert
    self.block.transactions = self.block.transactions[:txcount]
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/rlp/sedes/serializable.py", line 334, in field_fn_setter
    raise AttributeError("can't set attribute")
AttributeError: can't set attribute

======================================================================
ERROR: test_totalSupply (test.erc20_tests_1.TestSolidity2ERC20)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 424, in setUp
    super().setUp()
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 52, in setUp
    self.s.revert(self.initial_state)
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/ethereum/tools/tester.py", line 297, in revert
    self.block.transactions = self.block.transactions[:txcount]
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/rlp/sedes/serializable.py", line 334, in field_fn_setter
    raise AttributeError("can't set attribute")
AttributeError: can't set attribute

======================================================================
ERROR: test_transfer (test.erc20_tests_1.TestSolidity2ERC20)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 424, in setUp
    super().setUp()
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 52, in setUp
    self.s.revert(self.initial_state)
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/ethereum/tools/tester.py", line 297, in revert
    self.block.transactions = self.block.transactions[:txcount]
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/rlp/sedes/serializable.py", line 334, in field_fn_setter
    raise AttributeError("can't set attribute")
AttributeError: can't set attribute

======================================================================
ERROR: test_transferFromAndAllowance (test.erc20_tests_1.TestSolidity2ERC20)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 424, in setUp
    super().setUp()
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py", line 52, in setUp
    self.s.revert(self.initial_state)
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/ethereum/tools/tester.py", line 297, in revert
    self.block.transactions = self.block.transactions[:txcount]
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/rlp/sedes/serializable.py", line 334, in field_fn_setter
    raise AttributeError("can't set attribute")
AttributeError: can't set attribute

----------------------------------------------------------------------
Ran 18 tests in 0.353s

FAILED (errors=19)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
Finished Solidity-compatible ERC20 tests, Suite 1 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
Running Solidity-compatible ERC20 tests, Suite 2 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Initializing chain from provided state
Testing nonvyper/ERC20_solidity_2.sol
Deploying contract at 09f24956cac320a987934f5da542b19a4e1ff04e used 371261 gas
test_all (test.erc20_tests_2.ERC20_solidity_2_sol) ... ERROR
Initializing chain from provided state
Testing nonvyper/ERC20_solidity_1.sol
Deploying contract at 09f24956cac320a987934f5da542b19a4e1ff04e used 378559 gas
test_all (test.erc20_tests_2.ERC20_solidity_1_sol) ... ERROR

======================================================================
ERROR: test_all (test.erc20_tests_2.ERC20_solidity_2_sol)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_2.py", line 144, in setUp
    super().setUp()
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/utils/pyethereum_test_utils.py", line 54, in setUp
    self.s.revert(self.initial_state)
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/ethereum/tools/tester.py", line 297, in revert
    self.block.transactions = self.block.transactions[:txcount]
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/rlp/sedes/serializable.py", line 334, in field_fn_setter
    raise AttributeError("can't set attribute")
AttributeError: can't set attribute

======================================================================
ERROR: test_all (test.erc20_tests_2.ERC20_solidity_1_sol)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_2.py", line 144, in setUp
    super().setUp()
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/tests/examples/tokens/ERC20_solidity_compatible/utils/pyethereum_test_utils.py", line 54, in setUp
    self.s.revert(self.initial_state)
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/ethereum/tools/tester.py", line 297, in revert
    self.block.transactions = self.block.transactions[:txcount]
  File "/Users/ryuya.nakamura/work/nrryuya/vyper/venv/lib/python3.7/site-packages/rlp/sedes/serializable.py", line 334, in field_fn_setter
    raise AttributeError("can't set attribute")
AttributeError: can't set attribute

----------------------------------------------------------------------
Ran 2 tests in 0.244s

FAILED (errors=2)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
Finished Solidity-compatible ERC20 tests, Suite 2 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
FAILED : Test failures encounting, exiting with error.
```

**Comment by nrryuya** [comment]
#43
